# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/debug.xdc

# Block Designs: bd/MP0_design_1/MP0_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1 || ORIG_REF_NAME==MP0_design_1}]

# IP: bd/MP0_design_1/ip/MP0_design_1_processing_system7_0_0/MP0_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_processing_system7_0_0 || ORIG_REF_NAME==MP0_design_1_processing_system7_0_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_axi_gpio_0_0/MP0_design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_axi_gpio_0_0 || ORIG_REF_NAME==MP0_design_1_axi_gpio_0_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_axi_gpio_1_0/MP0_design_1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_axi_gpio_1_0 || ORIG_REF_NAME==MP0_design_1_axi_gpio_1_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_axi_gpio_2_0/MP0_design_1_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_axi_gpio_2_0 || ORIG_REF_NAME==MP0_design_1_axi_gpio_2_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_ps7_0_axi_periph_1/MP0_design_1_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_ps7_0_axi_periph_1 || ORIG_REF_NAME==MP0_design_1_ps7_0_axi_periph_1}]

# IP: bd/MP0_design_1/ip/MP0_design_1_rst_ps7_0_100M_1/MP0_design_1_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_rst_ps7_0_100M_1 || ORIG_REF_NAME==MP0_design_1_rst_ps7_0_100M_1}]

# IP: bd/MP0_design_1/ip/MP0_design_1_xbar_0/MP0_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_xbar_0 || ORIG_REF_NAME==MP0_design_1_xbar_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_axi_vdma_0_0/MP0_design_1_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_axi_vdma_0_0 || ORIG_REF_NAME==MP0_design_1_axi_vdma_0_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_v_tc_0_0/MP0_design_1_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_v_tc_0_0 || ORIG_REF_NAME==MP0_design_1_v_tc_0_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_v_axi4s_vid_out_0_0/MP0_design_1_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==MP0_design_1_v_axi4s_vid_out_0_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_xlconstant_0_0/MP0_design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_xlconstant_0_0 || ORIG_REF_NAME==MP0_design_1_xlconstant_0_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/MP0_design_1_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_smartconnect_0_0 || ORIG_REF_NAME==MP0_design_1_smartconnect_0_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_proc_sys_reset_0_0/MP0_design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==MP0_design_1_proc_sys_reset_0_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_xlconstant_1_0/MP0_design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_xlconstant_1_0 || ORIG_REF_NAME==MP0_design_1_xlconstant_1_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_xlslice_0_0/MP0_design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_xlslice_0_0 || ORIG_REF_NAME==MP0_design_1_xlslice_0_0}]

# IP: bd/MP0_design_1/ip/MP0_design_1_auto_pc_0/MP0_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP0_design_1_auto_pc_0 || ORIG_REF_NAME==MP0_design_1_auto_pc_0}]

# XDC: bd/MP0_design_1/MP0_design_1_ooc.xdc
