# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.cache/wt [current_project]
set_property parent.project_path C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/hdl/MP0_design_1_wrapper.vhd
add_files C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/MP0_design_1.bd
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_processing_system7_0_0/MP0_design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_gpio_0_0/MP0_design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_gpio_0_0/MP0_design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_gpio_0_0/MP0_design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_gpio_1_0/MP0_design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_gpio_1_0/MP0_design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_gpio_1_0/MP0_design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_gpio_2_0/MP0_design_1_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_gpio_2_0/MP0_design_1_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_gpio_2_0/MP0_design_1_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_rst_ps7_0_100M_1/MP0_design_1_rst_ps7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_rst_ps7_0_100M_1/MP0_design_1_rst_ps7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_rst_ps7_0_100M_1/MP0_design_1_rst_ps7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_xbar_0/MP0_design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_vdma_0_0/MP0_design_1_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_vdma_0_0/MP0_design_1_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_axi_vdma_0_0/MP0_design_1_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_v_tc_0_0/MP0_design_1_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_v_tc_0_0/MP0_design_1_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_v_axi4s_vid_out_0_0/MP0_design_1_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_v_axi4s_vid_out_0_0/MP0_design_1_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_4118_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_4118_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_4118_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_4118_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_4118_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_4118_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_proc_sys_reset_0_0/MP0_design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_proc_sys_reset_0_0/MP0_design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_proc_sys_reset_0_0/MP0_design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_auto_pc_0/MP0_design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/MP0_design_1_ooc.xdc]
set_property is_locked true [get_files C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/MP0_design_1.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/constrs_1/new/debug.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top MP0_design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef MP0_design_1_wrapper.dcp

catch { report_utilization -file MP0_design_1_wrapper_utilization_synth.rpt -pb MP0_design_1_wrapper_utilization_synth.pb }
