# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: U:/Documents/CprE 488/Labs/Cpre488/MP-1/CPRE_488_MP-1/MP-1.srcs/sources_1/bd/MP_1_Design_1/ip/MP_1_Design_1_processing_system7_0_0/MP_1_Design_1_processing_system7_0_0.xci
# IP: The module: 'MP_1_Design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/CprE 488/Labs/Cpre488/MP-1/CPRE_488_MP-1/MP-1.srcs/sources_1/bd/MP_1_Design_1/ip/MP_1_Design_1_processing_system7_0_0/MP_1_Design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP_1_Design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: U:/Documents/CprE 488/Labs/Cpre488/MP-1/CPRE_488_MP-1/MP-1.srcs/sources_1/bd/MP_1_Design_1/ip/MP_1_Design_1_processing_system7_0_0/MP_1_Design_1_processing_system7_0_0.xci
# IP: The module: 'MP_1_Design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/CprE 488/Labs/Cpre488/MP-1/CPRE_488_MP-1/MP-1.srcs/sources_1/bd/MP_1_Design_1/ip/MP_1_Design_1_processing_system7_0_0/MP_1_Design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP_1_Design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
