# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: u:/Documents/MP-4/MP-4.srcs/sources_1/bd/MP4_design1/ip/MP4_design1_xbar_0/MP4_design1_xbar_0.xci
# IP: The module: 'MP4_design1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/MP-4/MP-4.srcs/sources_1/bd/MP4_design1/ip/MP4_design1_xbar_0/MP4_design1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP4_design1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: u:/Documents/MP-4/MP-4.srcs/sources_1/bd/MP4_design1/ip/MP4_design1_xbar_0/MP4_design1_xbar_0.xci
# IP: The module: 'MP4_design1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/Documents/MP-4/MP-4.srcs/sources_1/bd/MP4_design1/ip/MP4_design1_xbar_0/MP4_design1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP4_design1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
