# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/MP0_design_1_smartconnect_0_0.xci
# IP: The module: 'MP0_design_1_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/bd_4118.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_4118_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_4118_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_4118_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_4118_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_4118_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_4118_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_4118_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_4118_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_4118_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_4118_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_4118_s00a2s_0_ooc.xdc

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_4118_m00s2a_0_ooc.xdc

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_4118_sarn_0_ooc.xdc

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_4118_srn_0_ooc.xdc

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_4118_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_4118_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_design_1_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/MP0_design_1_smartconnect_0_0.xci
# IP: The module: 'MP0_design_1_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/bd_4118.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_4118_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_4118_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_4118_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_4118_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_4118_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_4118_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_4118_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_4118_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_4118_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_4118_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_4118_s00a2s_0_ooc.xdc

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_4118_m00s2a_0_ooc.xdc

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_4118_sarn_0_ooc.xdc

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_4118_srn_0_ooc.xdc

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_4118_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_4118_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_design_1_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
