# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: U:/Desktop/MP-2/hw/fmc_imageon_gs/zedboard_fmc_imageon_gs.xdc

# Block Designs: U:/Desktop/MP-2/hw/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_fmc_imageon_iic_0_0/design_1_fmc_imageon_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fmc_imageon_iic_0_0 || ORIG_REF_NAME==design_1_fmc_imageon_iic_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_rst_clk_wiz_0_148M_0/design_1_rst_clk_wiz_0_148M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_148M_0 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_148M_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_v_tc_0_0/design_1_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_tc_0_0 || ORIG_REF_NAME==design_1_v_tc_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_v_axi4s_vid_out_0_0/design_1_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_avnet_hdmi_out_0_0/design_1_avnet_hdmi_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_avnet_hdmi_out_0_0 || ORIG_REF_NAME==design_1_avnet_hdmi_out_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_axi_vdma_0_0/design_1_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_vdma_0_0 || ORIG_REF_NAME==design_1_axi_vdma_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_0_0 || ORIG_REF_NAME==design_1_axis_subset_converter_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_fmc_ipmi_id_eeprom_0_0/design_1_fmc_ipmi_id_eeprom_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fmc_ipmi_id_eeprom_0_0 || ORIG_REF_NAME==design_1_fmc_ipmi_id_eeprom_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_onsemi_vita_spi_0_0/design_1_onsemi_vita_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_onsemi_vita_spi_0_0 || ORIG_REF_NAME==design_1_onsemi_vita_spi_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_onsemi_vita_cam_0_0/design_1_onsemi_vita_cam_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_onsemi_vita_cam_0_0 || ORIG_REF_NAME==design_1_onsemi_vita_cam_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_v_vid_in_axi4s_0_0/design_1_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==design_1_v_vid_in_axi4s_0_0}]

# IP: U:/Desktop/MP-2/hw/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0}]

# XDC: U:/Desktop/MP-2/hw/design_1/design_1_ooc.xdc
