# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: U:/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_processing_system7_0_0/MP0_design_1_processing_system7_0_0.xci
# IP: The module: 'MP0_design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_processing_system7_0_0/MP0_design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: U:/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_processing_system7_0_0/MP0_design_1_processing_system7_0_0.xci
# IP: The module: 'MP0_design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_processing_system7_0_0/MP0_design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
