# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_xbar_0/MP0_design_1_xbar_0.xci
# IP: The module: 'MP0_design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_xbar_0/MP0_design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_xbar_0/MP0_design_1_xbar_0.xci
# IP: The module: 'MP0_design_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/njknuth/CPR_E_488_git/MP-0/MP-0.srcs/sources_1/bd/MP0_design_1/ip/MP0_design_1_xbar_0/MP0_design_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP0_design_1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
