# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MP4_constraints.xdc

# Block Designs: bd/MP4_design1/MP4_design1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1 || ORIG_REF_NAME==MP4_design1}]

# IP: bd/MP4_design1/ip/MP4_design1_processing_system7_0_0/MP4_design1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_processing_system7_0_0 || ORIG_REF_NAME==MP4_design1_processing_system7_0_0}]

# IP: bd/MP4_design1/ip/MP4_design1_axi_gpio_0_1/MP4_design1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_axi_gpio_0_1 || ORIG_REF_NAME==MP4_design1_axi_gpio_0_1}]

# IP: bd/MP4_design1/ip/MP4_design1_axi_gpio_1_1/MP4_design1_axi_gpio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_axi_gpio_1_1 || ORIG_REF_NAME==MP4_design1_axi_gpio_1_1}]

# IP: bd/MP4_design1/ip/MP4_design1_axi_bram_ctrl_0_1/MP4_design1_axi_bram_ctrl_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_axi_bram_ctrl_0_1 || ORIG_REF_NAME==MP4_design1_axi_bram_ctrl_0_1}]

# IP: bd/MP4_design1/ip/MP4_design1_ps7_0_axi_periph_2/MP4_design1_ps7_0_axi_periph_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_ps7_0_axi_periph_2 || ORIG_REF_NAME==MP4_design1_ps7_0_axi_periph_2}]

# IP: bd/MP4_design1/ip/MP4_design1_rst_ps7_0_100M_2/MP4_design1_rst_ps7_0_100M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_rst_ps7_0_100M_2 || ORIG_REF_NAME==MP4_design1_rst_ps7_0_100M_2}]

# IP: bd/MP4_design1/ip/MP4_design1_axi_bram_ctrl_0_bram_2/MP4_design1_axi_bram_ctrl_0_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_axi_bram_ctrl_0_bram_2 || ORIG_REF_NAME==MP4_design1_axi_bram_ctrl_0_bram_2}]

# IP: bd/MP4_design1/ip/MP4_design1_xbar_0/MP4_design1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_xbar_0 || ORIG_REF_NAME==MP4_design1_xbar_0}]

# IP: bd/MP4_design1/ip/MP4_design1_auto_pc_1/MP4_design1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_auto_pc_1 || ORIG_REF_NAME==MP4_design1_auto_pc_1}]

# IP: bd/MP4_design1/ip/MP4_design1_auto_pc_0/MP4_design1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_auto_pc_0 || ORIG_REF_NAME==MP4_design1_auto_pc_0}]

# IP: bd/MP4_design1/ip/MP4_design1_auto_pc_2/MP4_design1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP4_design1_auto_pc_2 || ORIG_REF_NAME==MP4_design1_auto_pc_2}]

# XDC: bd/MP4_design1/MP4_design1_ooc.xdc
